#!/usr/bin/env bash
# scripts/configure-geoserver-security.sh
#
# Configures GeoServer Cloud security over the Bastion SOCKS5 tunnel (Option 1):
#   1. Request-header pre-auth filter (headerAuth) reading sec-username (= the
#      lower-cased IDIR email injected by the Node proxy).
#   2. headerAuth uses the BUILT-IN default XML role service (roleServiceName=default).
#      GeoServer Cloud 3.0 cannot load the JDBC (gssec) role/user-group services
#      (XStream `cannot be cast to JDBCSecurityServiceConfig`), so we use the XML
#      services that load reliably. Role assignment is done in the GeoServer UI/REST.
#   3. Cleans up any previously-uploaded JDBC role service + idir user/group service
#      files (both crash the Security page on load).
#   4. Wires headerAuth into the web/default/gwc/rest filter chains.
#      The rest chain MUST be included so that OIDC-authenticated browser sessions
#      can use the REST API without being asked for a username/password.
#   5. Bootstraps the super admin (ADMIN_PRINCIPAL email -> ROLE_ADMINISTRATOR).
#   6. Auth-key filter (authKey) for machine/API clients (?authkey=<key>), wired
#      ONLY into default+gwc (OWS/tiles) — GeoServer's authkey module is documented
#      as not working reliably against the admin GUI or the REST config API, so it
#      is deliberately excluded from the web/rest chains. See docs/node-oidc-proxy-
#      contract.md §5 and the proxy's MACHINE_AUTH_PASSTHROUGH knob, which is what
#      lets these requests reach GeoServer without the proxy injecting sec-username.
#      One shared filter/mapper, N machine-client users (MACHINE_CLIENT_USERNAMES) —
#      each gets its own key stored as a "UUID" user property in users.xml (see
#      §6 below for why PropertyAuthenticationKeyMapper/authkeys.properties was
#      abandoned). This step never grants roles: per-workspace authorization for
#      each username lives in geo-server-app-config/catalog/acl_rules.yaml instead
#      (see that file for why).
#   6e. Restarts the OWS Container Apps (wms/wfs/wcs/wps/gwc) if step 6 changed
#      any user or authkey. Writing users.xml via the Resource REST API only
#      updates whichever single pod served that HTTP call — GeoServer Cloud's
#      event bus (CloudGeoServerSecurityManager) only broadcasts service-level
#      config changes (filters, role/user-group SERVICE config), never user/
#      group DATA changes, and /rest/reload only reloads the one pod it hits.
#      Each OWS service is independently scaled (min_replicas>=1), so a new
#      authkey would otherwise silently only work on whichever pod happened to
#      serve the write. This holds regardless of XML vs JDBC backing store —
#      JDBC-backed security was investigated and rejected because none of the
#      stock OWS images bundle the gs-sec-jdbc engine (see step 1's comment),
#      and GeoServer's AbstractUserGroupService caches in memory either way —
#      so a hard restart of the OWS pods is the actual fix, not a workaround
#      pending a better one.
#   7. Verifies the result.
#
# Invoked by null_resource.configure_geoserver_security (stack/main.tf).
#
# Required env vars:
#   KV_NAME          Key Vault name (for the geoserver-admin-password secret)
#   GATEWAY_URL      e.g. https://gateway.<env-domain>  (NOT the .internal. form)
#   RESOURCE_GROUP   Azure resource group containing the OWS Container Apps
#                    (only required if MACHINE_CLIENT_USERNAMES is set, since
#                    it's only used to restart wms/wfs/wcs/wps/gwc after an
#                    authkey change — see step 6e above)
# Optional:
#   SOCKS5_PORT      default 8228
#   GS_BASE_PATH     default /geoserver/cloud
#   ADMIN_PRINCIPAL  email to bootstrap as ROLE_ADMINISTRATOR (e.g. omishra@gov.bc.ca)
#   ROLE_SERVICE     default "default"   (built-in XML role service)
#   UG_SERVICE       default "default"   (built-in XML user/group service)
#   MACHINE_CLIENT_USERNAMES  comma-separated service-account usernames for the
#                             authkey filter, one per workspace/dataset consumer
#                             (e.g. svc-machine-wildlife). Unset/empty -> step 6
#                             skipped entirely. This step provisions AUTHENTICATION
#                             ONLY (a user + its key) — AUTHORIZATION (which
#                             workspace/layer each username can read or write) is
#                             defined as a username-scoped rule in
#                             geo-server-app-config/catalog/acl_rules.yaml, applied
#                             separately via `geoserver-apply run <env>`. This script
#                             never grants roles to machine users.
#   (Each username's key is NOT an input — it's fetched per-username from the KV
#    secret "geoserver-machine-authkey-<username>", generated by
#    null_resource.secret_geoserver_machine_authkey["<username>"].)

set -euo pipefail

: "${KV_NAME:?KV_NAME is required}"
: "${GATEWAY_URL:?GATEWAY_URL is required}"
SOCKS5_PORT="${SOCKS5_PORT:-8228}"
GS_BASE_PATH="${GS_BASE_PATH:-/geoserver/cloud}"
ADMIN_PRINCIPAL="${ADMIN_PRINCIPAL:-}"
ROLE_SERVICE="${ROLE_SERVICE:-default}"
UG_SERVICE="${UG_SERVICE:-default}"
MACHINE_CLIENT_USERNAMES="${MACHINE_CLIENT_USERNAMES:-}"
RESOURCE_GROUP="${RESOURCE_GROUP:-}"

PROXY="socks5h://127.0.0.1:${SOCKS5_PORT}"
GS="${GATEWAY_URL}${GS_BASE_PATH}"

ADMIN_PASS="$(az keyvault secret show --vault-name "${KV_NAME}" --name geoserver-admin-password --query value -o tsv)"

# Fetched here (not passed through Terraform) so key values never touch
# Terraform state or logs, same rationale as ADMIN_PASS above. One secret per
# username: "geoserver-machine-authkey-<username>".
declare -A MACHINE_CLIENT_AUTHKEYS=()
if [ -n "${MACHINE_CLIENT_USERNAMES}" ]; then
  : "${RESOURCE_GROUP:?RESOURCE_GROUP is required when MACHINE_CLIENT_USERNAMES is set (needed to restart OWS pods after an authkey change — see step 6e)}"
  IFS=',' read -ra _machine_usernames <<< "${MACHINE_CLIENT_USERNAMES}"
  for _u in "${_machine_usernames[@]}"; do
    MACHINE_CLIENT_AUTHKEYS["${_u}"]="$(az keyvault secret show --vault-name "${KV_NAME}" --name "geoserver-machine-authkey-${_u}" --query value -o tsv 2>/dev/null || echo '')"
  done
fi

gs_curl() { curl --proxy "${PROXY}" -s --max-time 120 -u "admin:${ADMIN_PASS}" "$@"; }

TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

# Force-restarts wms/wfs/wcs/wps/gwc so they reload users.xml (see step 6e
# comment above). Talks to management.azure.com directly via ARM REST API
# rather than the `az containerapp` CLI extension: that extension has been
# unreliable in this environment (broken/locked azext_metadata.json on some
# machines), and management-plane calls don't need the SOCKS5 tunnel anyway
# (only data-plane calls to GeoServer/ACL/Postgres over the VNet do).
restart_ows_services() {
  local sub token app rev http i
  sub="$(az account show --query id -o tsv)"
  token="$(az account get-access-token --resource https://management.azure.com --query accessToken -o tsv)"
  for app in wms wfs wcs wps gwc; do
    rev="$(curl -s -H "Authorization: Bearer ${token}" \
      "https://management.azure.com/subscriptions/${sub}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.App/containerApps/${app}?api-version=2024-03-01" \
      | python -c 'import json,sys; print(json.load(sys.stdin)["properties"]["latestRevisionName"])' 2>/dev/null)"
    if [ -z "${rev}" ]; then
      echo "  WARNING: could not resolve latest revision for ${app} — skipping restart." >&2
      continue
    fi
    # Content-Length: 0 is required — ARM returns 411 on this empty-body POST
    # without it (curl doesn't send one by default for a bodyless -X POST).
    http="$(curl -s -o /dev/null -w '%{http_code}' -X POST -H "Authorization: Bearer ${token}" -H "Content-Length: 0" \
      "https://management.azure.com/subscriptions/${sub}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.App/containerApps/${app}/revisions/${rev}/restart?api-version=2024-03-01")"
    echo "  restart ${app} (revision ${rev}) -> HTTP ${http}"
    for i in $(seq 1 20); do
      state="$(curl -s -H "Authorization: Bearer ${token}" \
        "https://management.azure.com/subscriptions/${sub}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.App/containerApps/${app}/revisions/${rev}?api-version=2024-03-01" \
        | python -c 'import json,sys; d=json.load(sys.stdin)["properties"]; print(d.get("healthState"), d.get("runningState"))' 2>/dev/null || echo 'Unknown Unknown')"
      [ "${state}" = "Healthy Running" ] && { echo "    ${app} healthy after restart."; break; }
      [ "${i}" -eq 20 ] && echo "  WARNING: ${app} not confirmed healthy after restart (last state: ${state})." >&2
      sleep 6
    done
  done
}

# ---------------------------------------------------------------------------
# Wait for the GeoServer REST API (gateway/rest cold-start can take ~60s).
# ---------------------------------------------------------------------------
echo "Waiting for GeoServer REST API at ${GS} ..."
for i in $(seq 1 40); do
  http="$(gs_curl -o /dev/null -w '%{http_code}' "${GS}/rest/about/version.json" 2>/dev/null || echo 000)"
  if [ "${http}" = "200" ]; then echo "GeoServer is up (attempt ${i})."; break; fi
  echo "  attempt ${i}/40 -> HTTP ${http}, retrying in 15s..."
  sleep 15
  [ "${i}" -eq 40 ] && { echo "Timed out waiting for GeoServer." >&2; exit 1; }
done

# ---------------------------------------------------------------------------
# 1. Cleanup: remove broken JDBC security services that crash the Security page.
#    (The JDBC role service + the idir JDBC user/group service both fail to load
#    on GeoServer Cloud 3.0 with a ClassCastException.)
# ---------------------------------------------------------------------------
echo "Removing broken JDBC security service files (if present)..."
del() {
  local path="$1"
  local code
  code="$(gs_curl -o /dev/null -w '%{http_code}' -X DELETE "${GS}/rest/resource/${path}" 2>/dev/null || echo 000)"
  case "${code}" in
    2*|404) echo "  ${path}: ${code}" ;;
    *)      echo "  WARNING: DELETE ${path} returned ${code} (non-fatal)" ;;
  esac
}
for f in config.xml rolesddl.xml rolesdml.xml; do del "security/role/jdbc/${f}"; done
for f in config.xml usersdddl.xml usersdml.xml; do del "security/usergroup/idir/${f}"; done
echo "Reloading GeoServer after cleanup..."
gs_curl -X POST "${GS}/rest/reload" -w '  reload -> HTTP %{http_code}\n' || true

# ---------------------------------------------------------------------------
# 2. Request-header pre-auth filter.
#    roleSource=Header: the Node OIDC proxy injects sec-roles directly so
#    GeoServer does NOT need a role-service lookup per request.  The proxy
#    injects ROLE_ADMINISTRATOR for every authenticated IDIR session.
# ---------------------------------------------------------------------------
cat > "${TMP}/headerfilter.xml" <<FILTER
<org.geoserver.security.config.RequestHeaderAuthenticationFilterConfig>
  <name>headerAuth</name>
  <className>org.geoserver.security.filter.GeoServerRequestHeaderAuthenticationFilter</className>
  <roleServiceName>${ROLE_SERVICE}</roleServiceName>
  <principalHeaderAttribute>sec-username</principalHeaderAttribute>
  <rolesHeaderAttribute>sec-roles</rolesHeaderAttribute>
  <roleSource class="org.geoserver.security.config.PreAuthenticatedUserNameFilterConfig\$PreAuthenticatedUserNameRoleSource">Header</roleSource>
</org.geoserver.security.config.RequestHeaderAuthenticationFilterConfig>
FILTER

echo "Configuring headerAuth filter (roleSource=Header, rolesHeaderAttribute=sec-roles)..."
# A per-name GET of a missing filter returns "<null/>" with HTTP 200, so decide
# create vs update from the filter LIST.
if gs_curl "${GS}/rest/security/authfilters.xml" | grep -q "<name>headerAuth</name>"; then
  filter_method="PUT";  filter_url="${GS}/rest/security/authfilters/headerAuth"; filter_verb="update"
else
  filter_method="POST"; filter_url="${GS}/rest/security/authfilters";            filter_verb="create"
fi
filter_code="$(gs_curl -o "${TMP}/filter_resp.txt" -w '%{http_code}' \
  -X "${filter_method}" -H "Content-Type: application/xml" \
  --data-binary @"${TMP}/headerfilter.xml" "${filter_url}")"
echo "  headerAuth ${filter_verb} -> HTTP ${filter_code}"
case "${filter_code}" in
  2*) : ;;
  *) echo "  headerAuth ${filter_verb} FAILED:" >&2; sed 's/^/    /' "${TMP}/filter_resp.txt" >&2; exit 1 ;;
esac

# ---------------------------------------------------------------------------
# 3. Wire headerAuth into the web/default/gwc/rest filter chains.
# ---------------------------------------------------------------------------
echo "Wiring headerAuth into filter chains..."
gs_curl "${GS}/rest/resource/security/config.xml" -o "${TMP}/config.xml"

# Bash-native idempotency check: extract the lines for a specific <filters name="...">
# block and grep for the target filter.  No Python dependency.
chain_has_filter() {
  local chain="$1" filter="$2" file="$3"
  sed -n "/<filters name=\"${chain}\"[^>]*>/,/<\/filters>/p" "${file}" 2>/dev/null | \
    grep -q "<filter>${filter}</filter>"
}

changed=0
for chain in web default gwc rest; do
  if chain_has_filter "${chain}" "headerAuth" "${TMP}/config.xml"; then
    echo "  headerAuth already in ${chain} chain — skipping."
    continue
  fi
  before="$(wc -c < "${TMP}/config.xml")"
  sed -zi "s|<filters name=\"${chain}\" \([^>]*\)>|<filters name=\"${chain}\" \1><filter>headerAuth</filter>|" "${TMP}/config.xml"
  after="$(wc -c < "${TMP}/config.xml")"
  if [ "${after}" -gt "${before}" ]; then
    echo "  Injected headerAuth into ${chain} chain."
    changed=$((changed + 1))
  else
    echo "  WARNING: ${chain} chain not found in config.xml — skipping (non-fatal)."
  fi
done

if [ "${changed}" -gt 0 ]; then
  gs_curl -X PUT -H "Content-Type: application/xml" --data-binary @"${TMP}/config.xml" \
    "${GS}/rest/resource/security/config.xml" -w '  config.xml chains -> HTTP %{http_code}\n'
else
  echo "  All chains already configured — no upload needed."
fi
echo "Reloading GeoServer configuration..."
gs_curl -X POST "${GS}/rest/reload" -w '  reload -> HTTP %{http_code}\n' || true

# ---------------------------------------------------------------------------
# 4. Bootstrap the super admin (best-effort; the local 'admin' user can always
#    assign roles in the UI if this step can't associate the system role).
# ---------------------------------------------------------------------------
if [ -n "${ADMIN_PRINCIPAL}" ]; then
  echo "Bootstrapping super admin: ${ADMIN_PRINCIPAL}"
  # 4a. Ensure the user exists in the default user/group service (random unused pw).
  rand_pw="$(openssl rand -base64 24 | tr -d '/+=\n' | head -c 24)"
  uc="$(gs_curl -o /dev/null -w '%{http_code}' -X POST -H "Content-Type: application/json" \
    -d "{\"user\":{\"userName\":\"${ADMIN_PRINCIPAL}\",\"password\":\"${rand_pw}\",\"enabled\":true}}" \
    "${GS}/rest/security/usergroup/service/${UG_SERVICE}/users" 2>/dev/null || echo 000)"
  case "${uc}" in
    2*)     echo "  admin user created (${uc})" ;;
    409|500) echo "  admin user already exists (${uc})" ;;
    *)      echo "  WARNING: create admin user returned ${uc} (non-fatal)" ;;
  esac
  # 4b. Ensure ROLE_ADMINISTRATOR exists, then associate it with the admin user.
  #     GeoServer's interceptors use ROLE_ADMINISTRATOR for the admin bypass check.
  gs_curl -o /dev/null -w '  ensure ROLE_ADMINISTRATOR -> HTTP %{http_code}\n' \
    -X POST "${GS}/rest/security/roles/role/ROLE_ADMINISTRATOR" 2>/dev/null || true
  rc="$(gs_curl -o /dev/null -w '%{http_code}' -X POST \
    "${GS}/rest/security/roles/role/ROLE_ADMINISTRATOR/user/${ADMIN_PRINCIPAL}" 2>/dev/null || echo 000)"
  case "${rc}" in
    2*) echo "  associated ROLE_ADMINISTRATOR with ${ADMIN_PRINCIPAL} (${rc})" ;;
    *)  echo "  WARNING: could not associate ROLE_ADMINISTRATOR role (${rc}). Assign it in the UI as 'admin'." ;;
  esac
  gs_curl -X POST "${GS}/rest/reload" -o /dev/null || true
else
  echo "ADMIN_PRINCIPAL not set — skipping super-admin bootstrap."
fi

# ---------------------------------------------------------------------------
# 6. Auth-key filter for machine/API clients (?authkey=<key> query param).
#    GeoServer's authkey module is documented as OGC-services-only: it does
#    NOT work reliably against the admin GUI or the REST config API
#    (https://docs.geoserver.org/latest/en/user/extensions/authkey/index.html).
#    So it is wired ONLY into the default (OWS: wms/wfs/wcs/wps) and gwc
#    chains — never web or rest. A machine client that also needs REST/
#    catalog writes must use Basic auth against a local user, unaffected by
#    this filter, or an OIDC browser session.
#
#    Key storage uses the built-in userPropertyMapper (stores the key as a
#    "UUID" user property in users.xml), NOT propertyMapper. propertyMapper's
#    synchronize() writes security/usergroup/<UG_SERVICE>/authkeys.properties
#    via a raw java.io.File/FileOutputStream with no mkdirs() — on GeoServer
#    Cloud, each microservice pod has its own ephemeral local resourcestore
#    cache, and if that pod never happened to materialize the usergroup/
#    <UG_SERVICE>/ directory on disk first, the write throws
#    FileNotFoundException and the whole auth attempt 500s. userPropertyMapper
#    instead reads/writes through GeoServerUserGroupService/Store, the same
#    abstraction users.xml already loads through reliably on every pod.
#    "UUID" is not overridable per-filter-config — it's hardcoded on the
#    built-in userPropertyMapper Spring bean
#    (geoserver/geoserver src/extension/authkey/.../applicationContext.xml)
#    and AuthenticationKeyFilterConfig has no field for it; it's just the
#    property name we store the key under, not an actual UUID.
# ---------------------------------------------------------------------------
if [ -n "${MACHINE_CLIENT_USERNAMES}" ]; then
  echo "Configuring auth-key filter for machine clients: ${MACHINE_CLIENT_USERNAMES}"

  # 6a. Create/update the shared authKey filter (one filter/mapper for all clients).
  cat > "${TMP}/authkeyfilter.xml" <<FILTER
<org.geoserver.security.AuthenticationKeyFilterConfig>
  <name>authKey</name>
  <className>org.geoserver.security.GeoServerAuthenticationKeyFilter</className>
  <userGroupServiceName>${UG_SERVICE}</userGroupServiceName>
  <authKeyParamName>authkey</authKeyParamName>
  <authKeyMapperName>userPropertyMapper</authKeyMapperName>
</org.geoserver.security.AuthenticationKeyFilterConfig>
FILTER

  if gs_curl "${GS}/rest/security/authfilters.xml" | grep -q "<name>authKey</name>"; then
    authkey_method="PUT";  authkey_url="${GS}/rest/security/authfilters/authKey"; authkey_verb="update"
  else
    authkey_method="POST"; authkey_url="${GS}/rest/security/authfilters";        authkey_verb="create"
  fi
  authkey_code="$(gs_curl -o "${TMP}/authkey_resp.txt" -w '%{http_code}' \
    -X "${authkey_method}" -H "Content-Type: application/xml" \
    --data-binary @"${TMP}/authkeyfilter.xml" "${authkey_url}")"
  echo "  authKey filter ${authkey_verb} -> HTTP ${authkey_code}"
  case "${authkey_code}" in
    2*) : ;;
    *) echo "  authKey filter ${authkey_verb} FAILED:" >&2; sed 's/^/    /' "${TMP}/authkey_resp.txt" >&2; exit 1 ;;
  esac

  # 6b. Wire into default + gwc ONLY (see limitation note above).
  gs_curl "${GS}/rest/resource/security/config.xml" -o "${TMP}/config_authkey.xml"
  ak_changed=0
  for chain in default gwc; do
    if chain_has_filter "${chain}" "authKey" "${TMP}/config_authkey.xml"; then
      echo "  authKey already in ${chain} chain — skipping."
      continue
    fi
    before="$(wc -c < "${TMP}/config_authkey.xml")"
    # Insert authKey AFTER headerAuth, not before. headerAuth
    # (GeoServerRequestHeaderAuthenticationFilter, the gateway-shared-auth client
    # filter) clears any existing PreAuthenticatedAuthenticationToken whenever its
    # own x-gsc-username header doesn't match the current principal — including the
    # "no gateway SSO session, header sent empty" case. If authKey ran first and
    # authenticated a machine client, a second-place headerAuth would see the empty
    # header mismatch the authKey principal and wipe the security context, silently
    # downgrading the request to anonymous. Running headerAuth first means it only
    # ever acts as a no-op when its header is empty (nothing to clear yet), leaving
    # authKey's authentication intact.
    sed -zi "s|<filters name=\"${chain}\" \([^>]*\)><filter>headerAuth</filter>|<filters name=\"${chain}\" \1><filter>headerAuth</filter><filter>authKey</filter>|" "${TMP}/config_authkey.xml"
    after="$(wc -c < "${TMP}/config_authkey.xml")"
    if [ "${after}" -gt "${before}" ]; then
      echo "  Injected authKey into ${chain} chain."
      ak_changed=$((ak_changed + 1))
    else
      echo "  WARNING: ${chain} chain not found in config.xml — skipping (non-fatal)."
    fi
  done
  if [ "${ak_changed}" -gt 0 ]; then
    gs_curl -X PUT -H "Content-Type: application/xml" --data-binary @"${TMP}/config_authkey.xml" \
      "${GS}/rest/resource/security/config.xml" -w '  config.xml chains -> HTTP %{http_code}\n'
  else
    echo "  authKey chains already configured — no upload needed."
  fi

  # 6c/6d. Per machine client: ensure the user exists, then store its key as a
  #     "UUID" property on that user in users.xml (via the generic Resource REST
  #     API, same GET/mutate/PUT pattern as the config.xml chain edits above —
  #     this is what userPropertyMapper reads). Authorization is NOT handled
  #     here — each username gets its own scoped rule in
  #     geo-server-app-config/catalog/acl_rules.yaml, applied separately via
  #     `geoserver-apply run <env>`, so this script only ever creates identities.
  cat > "${TMP}/set_authkey_property.py" <<'PYEOF'
# Sets/updates the "UUID" property (the authkey, per userPropertyMapper's
# hardcoded property name) on one <user> element in a GeoServer users.xml,
# via the real XML API so unrelated users/attributes are left untouched.
import sys
import xml.etree.ElementTree as ET

NS = "http://www.geoserver.org/security/users"
ET.register_namespace("", NS)

path, username, authkey = sys.argv[1], sys.argv[2], sys.argv[3]
tree = ET.parse(path)
users = tree.getroot().find(f"{{{NS}}}users")

user_el = next((u for u in users.findall(f"{{{NS}}}user") if u.get("name") == username), None)
if user_el is None:
    sys.exit(f"user {username} not found in users.xml")

prop_el = next((p for p in user_el.findall(f"{{{NS}}}property") if p.get("name") == "UUID"), None)
if prop_el is None:
    prop_el = ET.SubElement(user_el, f"{{{NS}}}property")
    prop_el.set("name", "UUID")
    changed = True
else:
    changed = prop_el.text != authkey
prop_el.text = authkey

tree.write(path, xml_declaration=True, encoding="UTF-8")
# Consumed by the caller to decide whether the OWS pods need restarting
# (step 6e) — only an actual authkey change requires it.
print("CHANGED" if changed else "UNCHANGED")
PYEOF

  authkey_data_changed=0
  IFS=',' read -ra _machine_usernames <<< "${MACHINE_CLIENT_USERNAMES}"
  for username in "${_machine_usernames[@]}"; do
    username="$(echo "${username}" | xargs)"
    [ -z "${username}" ] && continue

    authkey="${MACHINE_CLIENT_AUTHKEYS[${username}]:-}"
    if [ -z "${authkey}" ]; then
      echo "  WARNING: no geoserver-machine-authkey-${username} secret found in ${KV_NAME} — skipping ${username}." >&2
      continue
    fi

    rand_pw="$(openssl rand -base64 24 | tr -d '/+=\n' | head -c 24)"
    muc="$(gs_curl -o /dev/null -w '%{http_code}' -X POST -H "Content-Type: application/json" \
      -d "{\"user\":{\"userName\":\"${username}\",\"password\":\"${rand_pw}\",\"enabled\":true}}" \
      "${GS}/rest/security/usergroup/service/${UG_SERVICE}/users" 2>/dev/null || echo 000)"
    case "${muc}" in
      2*)      echo "  machine user ${username} created (${muc})"; authkey_data_changed=1 ;;
      409|500) echo "  machine user ${username} already exists (${muc})" ;;
      *)       echo "  WARNING: create machine user ${username} returned ${muc} (non-fatal)" ;;
    esac

    # Fetch/mutate/PUT users.xml per-username so a user created just above is
    # always present in the copy we mutate (no cross-iteration staleness).
    gs_curl "${GS}/rest/resource/security/usergroup/${UG_SERVICE}/users.xml" -o "${TMP}/users.xml"
    prop_state="$(python "${TMP}/set_authkey_property.py" "${TMP}/users.xml" "${username}" "${authkey}")"
    [ "${prop_state}" = "CHANGED" ] && authkey_data_changed=1
    ugc="$(gs_curl -o /dev/null -w '%{http_code}' -X PUT -H "Content-Type: application/xml" \
      --data-binary @"${TMP}/users.xml" \
      "${GS}/rest/resource/security/usergroup/${UG_SERVICE}/users.xml")"
    echo "  users.xml UUID property for ${username} -> HTTP ${ugc} (${prop_state})"
  done

  gs_curl -X POST "${GS}/rest/reload" -w '  reload -> HTTP %{http_code}\n' || true

  if [ "${authkey_data_changed}" = "1" ]; then
    echo "Machine-client user/authkey data changed — restarting OWS pods (wms/wfs/wcs/wps/gwc) so they pick up users.xml (see step 6e comment)..."
    restart_ows_services
  else
    echo "No machine-client user/authkey data changed — skipping OWS pod restart."
  fi
else
  echo "MACHINE_CLIENT_USERNAMES not set — skipping auth-key filter setup."
fi

# ---------------------------------------------------------------------------
# 7. Verify.
# ---------------------------------------------------------------------------
echo "Verifying..."
fail=0
check() {
  if gs_curl "${GS}${1}" | grep -q "${2}"; then echo "  OK   ${3}"; else echo "  FAIL ${3}"; fail=1; fi
}
check "/rest/security/authfilters.xml"     "headerAuth"          "headerAuth filter present"
check "/rest/security/authfilters/headerAuth.xml" "<rolesHeaderAttribute>sec-roles</rolesHeaderAttribute>" "headerAuth roleSource=Header with sec-roles attribute"
check "/rest/resource/security/config.xml" "headerAuth"          "headerAuth wired into chains"
# Default user/group service reachable (Security page health) + user count.
if gs_curl "${GS}/rest/security/usergroup/service/${UG_SERVICE}/users.json" -o "${TMP}/ug.json" 2>/dev/null \
   && grep -q 'userName\|"users"\|<users' "${TMP}/ug.json"; then
  echo "  OK   ${UG_SERVICE} user/group service reachable ($(grep -o 'userName' "${TMP}/ug.json" | wc -l | tr -d ' ') user(s))"
else
  echo "  WARN ${UG_SERVICE} user/group service not reachable"
fi
# Broken JDBC services must be gone.
if gs_curl "${GS}/rest/resource/security/role/jdbc/config.xml" 2>/dev/null | grep -q "JDBCRoleService"; then
  echo "  FAIL broken jdbc role service still present"; fail=1
else
  echo "  OK   broken jdbc role service absent"
fi

if [ -n "${MACHINE_CLIENT_USERNAMES}" ]; then
  check "/rest/security/authfilters.xml"     "authKey"             "authKey filter present"
  gs_curl "${GS}/rest/resource/security/config.xml" -o "${TMP}/config_verify.xml"
  if chain_has_filter "default" "authKey" "${TMP}/config_verify.xml" && chain_has_filter "gwc" "authKey" "${TMP}/config_verify.xml"; then
    echo "  OK   authKey wired into default+gwc chains"
  else
    echo "  FAIL authKey not wired into default+gwc chains"; fail=1
  fi
  if chain_has_filter "web" "authKey" "${TMP}/config_verify.xml" || chain_has_filter "rest" "authKey" "${TMP}/config_verify.xml"; then
    echo "  FAIL authKey unexpectedly present in web/rest chain (should be OWS-only)"; fail=1
  else
    echo "  OK   authKey absent from web/rest chains (matches documented OGC-only scope)"
  fi
  IFS=',' read -ra _verify_usernames <<< "${MACHINE_CLIENT_USERNAMES}"
  for username in "${_verify_usernames[@]}"; do
    username="$(echo "${username}" | xargs)"
    [ -z "${username}" ] && continue
    key="${MACHINE_CLIENT_AUTHKEYS[${username}]:-}"
    [ -z "${key}" ] && continue
    # Fixed-string match (grep -F) since the key is an arbitrary secret value,
    # not something safe to treat as a regex pattern.
    if gs_curl "${GS}/rest/resource/security/usergroup/${UG_SERVICE}/users.xml" 2>/dev/null | grep -qF "${key}"; then
      echo "  OK   users.xml stores authkey as a UUID property for ${username}"
    else
      echo "  FAIL users.xml missing authkey property for ${username}"; fail=1
    fi
  done
fi

[ "${fail}" != "0" ] && { echo "Security verification FAILED." >&2; exit 1; }
echo "GeoServer security configuration complete."
