global:
  config:
    dbName: geoserver

crunchy:
  enabled: true
  fullnameOverride: ""
  nameOverride: ""
  serviceAccount:
    create: false
    name: default
  postgresVersion: 18
  postGISVersion: "3.6"
  imagePullPolicy: IfNotPresent
  image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-postgres-gis:ubi9-18.1-3.6-2547

  clone:
    enabled: false
    path: ""
    s3:
      enabled: false
    pvc:
      enabled: false
      clusterName: ""

  restore:
    enabled: false
    repoName: repo1
    target: ""

  instances:
    name: db
    replicas: 2
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    dataVolumeClaimSpec:
      storage: 1Gi
      walStorage: 1Gi
      storageClassName: netapp-block-standard
    requests:
      cpu: 500m
      memory: 2Gi
    replicaCertCopy:
      requests:
        cpu: 50m
        memory: 64Mi

  pgBackRest:
    enabled: true
    backupPath: /backups/geoserver-cloud/cluster/version
    clusterCounter: 1
    retentionFullType: time
    s3:
      enabled: false
      retention: 7
      bucket: ""
      endpoint: ""
      accessKey: ""
      secretKey: ""
      region: ca-central-1
      fullBackupSchedule: "0 9 * * *"
      incrementalBackupSchedule: "0 */4 * * *"
    pvc:
      retention: 7
      retentionFullType: time
      fullBackupSchedule: "0 8 * * *"
      incrementalBackupSchedule: "0 0,4,8,12,16,20 * * *"
      volume:
        accessModes: ReadWriteOnce
        storage: 1Gi
        storageClassName: netapp-file-backup
    repoHost:
      requests:
        cpu: 100m
        memory: 128Mi
    sidecars:
      requests:
        cpu: 50m
        memory: 128Mi
    jobs:
      requests:
        cpu: 20m
        memory: 128Mi

  patroni:
    postgresql:
      pg_hba:
        - host all all 10.0.0.0/8 scram-sha-256
        - host all all ::1/128 scram-sha-256
      parameters:
        log_min_duration_statement: 1000ms
        shared_buffers: 512MB
        wal_buffers: 16MB
        work_mem: 4MB
        min_wal_size: 1GB
        max_wal_size: 4GB
        max_slot_wal_keep_size: 2GB
        effective_io_concurrency: 20

  proxy:
    enabled: true
    pgBouncer:
      image: ""
      replicas: 1
      requests:
        cpu: 50m
        memory: 128Mi
      maxConnections: 100

  pgmonitor:
    enabled: false
    exporter:
      image: ""
      requests:
        cpu: 10m
        memory: 32Mi

  users:
    - name: geoserver
      databases:
        - geoserver
    - name: postgres
      databases:
        - postgres
        - geoserver
    - name: geoserverproxy
      databases:
        - geoserver
        - postgres

  shutdown: false
  standby:
    enabled: false
    repoName: repo1
