{{- range $name, $service := .Values.services }}
{{- $config := mergeOverwrite (deepCopy $.Values.serviceDefaults) $service }}
{{- if or (and $config.autoscaling.enabled (gt (int $config.autoscaling.minReplicas) 1)) (and (not $config.autoscaling.enabled) (gt (int $config.replicas) 1)) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  labels:
    {{- include "geoserver-cloud.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "geoserver-cloud.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $name }}
{{- end }}
{{- end }}
{{- if and .Values.proxy.enabled (or (and .Values.proxy.autoscaling.enabled (gt (int .Values.proxy.autoscaling.minReplicas) 1)) (and (not .Values.proxy.autoscaling.enabled) (gt (int .Values.proxy.replicas) 1))) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.proxy.serviceName }}
  labels:
    {{- include "geoserver-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: oidc-proxy
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "geoserver-cloud.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: oidc-proxy
{{- end }}
